services:
  - type: web
    name: mockupsai-backend
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      prisma generate
      chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        sync: false