services:
  - type: web
    name: mockupsai-backend
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      prisma generate
      prisma py fetch --force
      chmod +x start.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 5371
    envVars:
      - key: DATABASE_URL
        sync: false